import fatima from '../asset/testimonial/fatima.svg';
import josh from '../asset/testimonial/josh.svg';
import alice from '../asset/testimonial/alice.svg';
import john from '../asset/testimonial/micheal.svg';

export const testimonials = [
  {
    id: 1,
    title: 'Efficiency Boost',
    avatar: fatima,
    avaterName: 'Fatima A',
    position: 'Sales Director @ Microsoft',
    description: '“Before Zentra, we were wasting time on scattered tools. Now, our whole sales process feels smooth, faster, and honestly way more productive than ever”',
  },
  {
    id: 2,
    title: 'Easy Integration',
    avatar: josh,
    avaterName: 'Josh T.',
    position: 'Co-Founder @ Heavy Tech',
    description: '"We were up and running in less than an hour. It connected perfectly with our tools, and our team didn’t need any extra training."',
  },
  {
    id: 3,
    title: 'Unified Workflow',
    avatar: alice,
    avaterName: 'Alice D.',
    position: 'CTO @ Innovate Labs',
    description: '"Finally, our marketing, sales, and support teams are all in sync. It’s been a huge relief to stop bouncing between platforms."',
  },
  {
    id: 4,
    title: 'Exceptional Support',
    avatar: john,
    avaterName: 'John R.',
    position: 'Lead Engineer @ Tech Solutions',
    description: '“With Zentra, our operations are more efficient, and we no longer struggle to manage tasks across multiple platforms.”',
  },
  {
    id: 5,
    title: 'Exceptional Support',
    avatar: fatima,
    avaterName: 'Fatima A',
    position: 'Sales Director @ Microsoft',
    description: '“Before Zentra, we were wasting time on scattered tools. Now, our whole sales process feels smooth, faster, and honestly way more productive than ever”',
  },
  {
    id: 6,
    title: 'Team Adoption',
    avatar: josh,
    avaterName: 'Josh T.',
    position: 'Co-Founder @ Heavy Tech',
    description: '"We’ve tried a few CRMs before, but this one actually stuck. Everyone on our team uses it with no complaints, no confusion, just results."',
  },
  {
    id: 7,
    title: 'Exceptional Support',
    avatar: alice,
    avaterName: 'Alice D.',
    position: 'CTO @ Innovate Labs',
    description: '“Zentra has cut down our processing time by half. We are now able to focus more on scaling the business.”',
  },
  {
    id: 8,
    title: 'Team Adoption',
    avatar: john,
    avaterName: 'Michael L.',
    position: 'CEO @ Grimaldi Inc.',
    description: '“With Zentra, our operations are more efficient, and we no longer struggle to manage tasks across multiple platforms.”',
  },
  {
    id: 9,
    title: 'Team Adoption',
    avatar: fatima,
    avaterName: 'Fatima A',
    position: 'Sales Director @ Microsoft',
    description: '“Before Zentra, we were wasting time on scattered tools. Now, our whole sales process feels smooth, faster, and honestly way more productive than ever”',
  },
  {
    id: 10,
    title: 'Efficiency',
    avatar: josh,
    avaterName: 'Josh T.',
    position: 'Co-Founder @ Heavy Tech',
    description: '“We were up and running in less than an hour. It connected perfectly with our tools, and our team didn’t need any extra training."',
  },
  {
    id: 11,
    title: 'Easy Integration',
    avatar: alice,
    avaterName: 'Alice D.',
    position: 'CTO @ Innovate Labs',
    description: '“Zentra has cut down our processing time by half. We are now able to focus more on scaling the business.”',
  },
  {
    id: 12,
    title: 'Efficiency',
    avatar: john,
    avaterName: 'John R.',
    position: 'Lead Engineer @ Tech Solutions',
    description: '“With Zentra, our operations are more efficient, and we no longer struggle to manage tasks across multiple platforms.”',
  },
  {
    id: 13,
    title: 'Efficiency',
    avatar: fatima,
    avaterName: 'Fatima A',
    position: 'Sales Director @ Microsoft',
    description: '“Before Zentra, we were wasting time on scattered tools. Now, our whole sales process feels smooth, faster, and honestly way more productive than ever”',
  },
  {
    id: 14,
    title: 'Easy Integration',
    avatar: josh,
    avaterName: 'Josh T.',
    position: 'Co-Founder @ Heavy Tech',
    description: '“We were up and running in less than an hour. It connected perfectly with our tools, and our team didn’t need any extra training."',
  },
  {
    id: 15,
    title: 'Unified Workflow',
    avatar: alice,
    avaterName: 'Alice D.',
    position: 'CTO @ Innovate Labs',
    description: '“Zentra has cut down our processing time by half. We are now able to focus more on scaling the business.”',
  },
  {
    id: 16,
    title: 'Efficiency Boost 16',
    avatar: john,
    avaterName: 'John R.',
    position: 'Lead Engineer @ Tech Solutions',
    description: '“With Zentra, our operations are more efficient, and we no longer struggle to manage tasks across multiple platforms.”',
  },
  {
    id: 17,
    title: 'Unified Workflow',
    avatar: fatima,
    avaterName: 'Fatima A',
    position: 'Sales Director @ Microsoft',
    description: '“Before Zentra, we were wasting time on scattered tools. Now, our whole sales process feels smooth, faster, and honestly way more productive than ever”',
  },
  {
    id: 18,
    title: 'Easy Integration',
    avatar: josh,
    avaterName: 'Josh T.',
    position: 'Co-Founder @ Heavy Tech',
    description: '“We were up and running in less than an hour. It connected perfectly with our tools, and our team didn’t need any extra training."',
  },
  {
    id: 19,
    title: 'Unified Workflow',
    avatar: alice,
    avaterName: 'Alice D.',
    position: 'CTO @ Innovate Labs',
    description: '“Zentra has cut down our processing time by half. We are now able to focus more on scaling the business.”',
  },
  {
    id: 20,
    title: 'Easy Integration',
    avatar: john,
    avaterName: 'John R.',
    position: 'Lead Engineer @ Tech Solutions',
    description: '“With Zentra, our operations are more efficient, and we no longer struggle to manage tasks across multiple platforms.”',
  },
];
